<?php


?>

<div class="content-header">

    <table cellspacing="0">

        <tr>

            <td style="width:50%;"><h3 class="icon-head"><?php echo Mage::helper('customoptions')->__('Manage Option Templates') ?></h3></td>

            <td class="form-buttons">

            	<?php echo $this->getAddNewButtonHtml() ?>

            </td>

        </tr>

    </table>

</div>

<div><?php echo $this->getGridHtml() ?></div>